baseURL = 'https://ccwavrin.fr'
languageCode = 'fr-fr'
title = 'Archives du C.C.Wavrin'
theme = 'hugo-theme-stack'

[params]
  description = "Archives du site C.C.Wavrin"
  mainSections = ["news", "courses", "vtt", "cyclotourisme", "cyclosportive", "triathlon", "club", "randonnee", "grand-prix", "documents"]

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 10 }  }
    ]
    page = [
      { type = "search" },
      { type = "archives", params = { limit = 10 }  }
    ]

  [params.sidebar.avatar]
    src = "ccwavrin.png"
    alt = "Cyclo Club Wavrin"

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Actualités"
    url = "/news/"
    weight = 2

  [[menu.main]]
    name = "Courses"
    url = "/courses/"
    weight = 3

  [[menu.main]]
    name = "VTT"
    url = "/vtt/"
    weight = 4

  [[menu.main]]
    name = "Cyclotourisme"
    url = "/cyclotourisme/"
    weight = 5

  [[menu.main]]
    name = "École de cyclisme"
    url = "/jeunes/"
    weight = 6

  [[menu.main]]
    name = "Triathlon"
    url = "/triathlon/"
    weight = 7

  [[menu.main]]
    name = "Cyclosportive"
    url = "/cyclosportive/"
    weight = 8

  [[menu.main]]
    name = "Le Club"
    url = "/club/"
    weight = 9

  [[menu.main]]
    name = "Grand prix"
    url = "/grand-prix/"
    weight = 10

  [[menu.main]]
    name = "Randonnée"
    url = "/randonnee/"
    weight = 11

  [[menu.main]]
    name = "Documents"
    url = "/documents/"
    weight = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

